#version 450

#extension GL_GOOGLE_include_directive  : require

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0) uniform sampler2D inputImage;
layout (binding = 1, rgba32f) uniform image2D resultImage;
layout (binding = 2) uniform Texture { uvec2 size; } tex;

#include "common/constants.glsl"
#include "common/math.glsl"

void main() {
    vec2 uv = vec2(gl_GlobalInvocationID.x / float(tex.size.x), gl_GlobalInvocationID.y / float(tex.size.y));

    vec3 direction = equalAreaSquareToSphere(uv);

    uv.x = (1.0 + atan(-direction.y, -direction.x) * M_1_PI) * 0.5;
    uv.y = acos(direction.z) * M_1_PI;

    vec4 color = texture(inputImage, uv);
    imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), color);
}