#version 460
#extension GL_GOOGLE_include_directive                      : require
#extension GL_EXT_ray_tracing                               : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64    : require
#extension GL_EXT_scalar_block_layout                       : require
//#ifdef MARI_DEBUG 
#extension GL_EXT_debug_printf                              : enable
//#endif

#include "common/material.glsl"
MaterialConstants material;
#include "common/sampling.glsl"
#include "common/tonemapping.glsl"
#include "common/light.glsl"
#include "common/volume.glsl"

layout(binding = 0, set = 0) uniform accelerationStructureEXT tlas;
layout(binding = 1, set = 0, rgba32f) uniform image2D image;
layout(binding = 2, set = 0, rgba8) uniform image2D present_image;
layout(binding = 8, set = 0) uniform sampler2D textures[];

layout(location = 0) rayPayloadEXT Payload prd;

layout(binding = 3, set = 0, scalar) uniform Properties {
    mat4  view_inverse;
    mat4  proj_inverse;
    int   frame_count;
    int   max_depth;
    float exposure;
    int   tonemapper;
    int   frame_accumulation;
    int   russian_roulette;
    int   next_event_estimation;
    int   samples_per_pixel;
} properties;


#define ERROR_COLOR vec3(5000.0, 0.0, 5000.0)

void main() {
    prd.seed = tea(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, properties.frame_count);
    vec3 result = vec3(0.0);

    const float tmin = 0.0;
    const float tmax = 10000.0;

    initialize_volume_nano();
    Medium medium;
    medium.absorption_color = vec3(0.7, 1.0, 0.9);
    medium.absorption = volume.sigma_a;
    medium.scattering = volume.sigma_s;
    medium.g = volume.g;
    medium.majorant = medium.absorption + medium.scattering;
    medium_push(medium);

    for (int sample_count = 0; sample_count < properties.samples_per_pixel; sample_count++) {
        const vec2 pixel_jitter = random2D(prd.seed);
        const vec2 pixel_center = vec2(gl_LaunchIDEXT.xy) + pixel_jitter;
        const vec2 s = (pixel_center / vec2(gl_LaunchSizeEXT.xy)) * 2.0 - 1.0;

        vec4 target     =  properties.proj_inverse * vec4(s.x, s.y, 1, 1);
        vec3 origin     = (properties.view_inverse * vec4(0, 0, 0, 1)).xyz;
        vec3 direction  = (properties.view_inverse * vec4(normalize(target.xyz), 0)).xyz;
        vec3 radiance   = vec3(0.0);
        vec3 throughput = vec3(1.0);
        bool is_volume  = false;

        for (uint depth = 0; depth < properties.max_depth; depth++) {
            float t = tmax;
            traceRayEXT(tlas, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, origin, tmin, direction, t, 0);
            
            Hit hit;
            if (prd.instance_index >= 0) {
                hit = process_hit(prd);
                t = length(hit.position - origin);
                material = hit.material;
            }

            //if (is_volume) {

            MediumSample medium_sample = sample_medium_along_ray(origin, direction, t, medium.majorant, prd.seed);

            if (medium_sample.terminated) {
                radiance   += throughput * medium_sample.emission;
                break;
            }
            if (medium_sample.scattered) {
                // Set values for next ray
                origin     = origin + direction * medium_sample.t;
                direction  = medium_sample.pf.wi;
                throughput *= medium_sample.pf.p / medium_sample.pf.pdf;
                continue;
            }

            //}

            // Miss. Sample environment map
            if (prd.instance_index < 0) {
                vec2 uv;
                vec3 le = sample_Le_infinite(direction, uv);
                radiance += throughput * le;
                break;
            } else {
                radiance += throughput * material.emission.rgb;
                break;
            }

            // Apply russian roulette
            float probability = max(max(throughput.r, throughput.g), throughput.b);
            if (properties.russian_roulette == 1 && probability < 1.0 && depth > 3) {
                
                if (random1D(prd.seed) > probability) {
                    break;
                }
                throughput /= probability;
            }
        }

        result += radiance;
    }

    result /= properties.samples_per_pixel;

    if (isnan(result.r) || isnan(result.g) || isnan(result.b)) result = ERROR_COLOR;
    if (isinf(result.r) || isinf(result.g) || isinf(result.b)) result = ERROR_COLOR;

    if (properties.frame_accumulation == 1) {
        // Load existing accumulated color
        vec4 previous_color = vec4(0.0);
        if (properties.frame_count > 0) {
            previous_color = imageLoad(image, ivec2(gl_LaunchIDEXT.xy));
        }

        // Calculate new average color
        float avg = 1.0 / (properties.frame_count + 1.0);
        result = (result + previous_color.rgb * properties.frame_count) * avg;
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(result, 1.0));
    }

    // Apply tone mapping
    vec3 tonemapped_color = apply_tonemapping(properties.tonemapper, result, properties.exposure);
    imageStore(present_image, ivec2(gl_LaunchIDEXT.xy), vec4(tonemapped_color, 1.0));
}