#version 460
#extension GL_GOOGLE_include_directive : require
//#ifdef MARI_DEBUG 
#extension GL_EXT_debug_printf         : enable
//#endif

#include "common/material.glsl"
MaterialConstants material;
#include "common/bxdf.glsl"
#include "common/sampling.glsl"
#include "common/raycommon.glsl"
#include "common/hitcommon.glsl"
#include "common/tonemapping.glsl"
#include "common/light.glsl"
#include "common/volume.glsl"

layout(binding = 0, set = 0) uniform accelerationStructureEXT tlas;
layout(binding = 1, set = 0, rgba32f) uniform image2D image;
layout(binding = 2, set = 0, rgba8) uniform image2D present_image;

layout(location = 0) rayPayloadEXT Payload prd;
layout(location = 1) rayPayloadEXT ShadowPayload shadow_prd;

layout(binding = 3, set = 0, scalar) uniform Properties {
    mat4  view_inverse;
    mat4  proj_inverse;
    int   frame_count;
    int   max_depth;
    float exposure;
    int   tonemapper;
    int   frame_accumulation;
    int   russian_roulette;
    int   next_event_estimation;
    int   samples_per_pixel;
} properties;

#define ERROR_COLOR vec3(5000.0, 0.0, 5000.0)

void main() {
    prd.seed = tea(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, properties.frame_count);
    vec3 result = vec3(0.0);

    initialize_volume_nano();

    const float tmin = 0.0;
    const float tmax = 10000.0;

    for (int sample_count = 0; sample_count < properties.samples_per_pixel; sample_count++) {
        const vec2 pixel_jitter = random2D(prd.seed);
        const vec2 pixel_center = vec2(gl_LaunchIDEXT.xy) + pixel_jitter;
        const vec2 s = (pixel_center / vec2(gl_LaunchSizeEXT.xy)) * 2.0 - 1.0;

        vec4 target     = properties.proj_inverse * vec4(s.x, s.y, 1, 1);
        vec3 origin     = (properties.view_inverse * vec4(0, 0, 0, 1)).xyz;
        vec3 direction  = (properties.view_inverse * vec4(normalize(target.xyz), 0)).xyz;
        vec3 radiance   = vec3(0.0);
        vec3 throughput = vec3(1.0);
        
        float eta_scale         = 1.0;
        float previous_pdf      = 1.0;
        bool  is_dirac_delta    = false;

        for (uint depth = 0; depth < properties.max_depth; depth++) {
            traceRayEXT(tlas, gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, origin, tmin, direction, tmax, 0);

            // Miss. Sample environment map // TODO move this to bottom so it matches the volumetric integrators
            if (prd.instance_index < 0) {
                vec2 uv;
                vec3 le = sample_Le_infinite(direction, uv);

                float mis_weight = 1.0;
                if (!is_dirac_delta && depth != 0 && properties.next_event_estimation == 1) {
                    mis_weight = power_heuristic(previous_pdf, pdf_light_infinite(uv));
                }

                if (!isnan(mis_weight)) radiance += throughput * le * mis_weight;
                break;
            }

            Hit hit = process_hit(prd);
            material = hit.material; // TODO remove global material
            const float distance = length(hit.position - origin);

            // Hit a volume boundary. Keep going without interacting.
            if (hit.material_type == MaterialType_Boundary) {
                bool entering = dot(direction, -hit.normal_g) > 0.0;

                //origin = hit.position + direction * 0.001;
                origin = offset_position(hit.position, entering ? -hit.normal_g : hit.normal_g);
                if (entering) {
                    medium_push(
                        hit.material.absorption.rgb,
                        hit.material.absorption.w,
                        hit.material.scattering,
                        hit.material.absorption.w + hit.material.scattering,
                        0.0
                    );
                } else {
                    // Process transmission from existing medium
                    if (current_medium >= 0) {
                        throughput *= get_transmittance(media[current_medium], distance);
                    }
                    medium_remove();
                }

                continue;
            }

            // Render backfaces
            if (dot(direction, hit.normal_g) > 0.0 && hit.material_type != MaterialType_Dielectric) {
                flip_orientation(hit);
            }

            const bool is_emissive = length_squared(hit.material.emission.rgb) > 0.0;

            // Sample indirect light
            if (is_emissive) {
                if (depth == 0 || is_dirac_delta || properties.next_event_estimation == 0) {
                    // TODO if single side -> if dot(normal_g, -prd.direction) > 0.0
                    radiance += throughput * hit.material.emission.rgb;
                }
                else {
                    float light_mis = pdf_light_area(hit.vertices, direction, distance, hit.material.emission.rgb, true); // TODO double sided parameter in material
                    float bxdf_mis = previous_pdf;
                    radiance += throughput * hit.material.emission.rgb * power_heuristic(bxdf_mis, light_mis);
                }
            }

            // Sample bxdf
            vec3 wo = to_local(hit.tangent, hit.bitangent, hit.normal_s, -direction);
            BxdfSample bxdf_sample = bxdf_sample_material(hit.material_type, wo, prd.seed);
            if (bxdf_sample.failed) {
                break;
            }

            // Set values for next ray
            throughput    *= hit.material.albedo.rgb;
            is_dirac_delta = bxdf_sample.is_dirac_delta;
            previous_pdf   = bxdf_sample.pdf;
            direction      = from_local(hit.tangent, hit.bitangent, hit.normal_s, bxdf_sample.wi);
            // If next ray goes inside non dielectric object, consider it absorbed
            bool going_inside = dot(direction, hit.normal_g) < 0.0;
            if (hit.material_type != MaterialType_Dielectric && going_inside) break;
            origin = offset_position(hit.position, going_inside ? -hit.normal_g : hit.normal_g);

            // Process transmission from existing medium
            if (current_medium >= 0) {
                throughput *= get_transmittance(media[current_medium], distance);
            }

            // Add or remove medium in stack when entering or exiting dielectric
            if (bxdf_sample.is_transmission) {
                if (going_inside) {
                    medium_push(
                        hit.material.absorption.rgb,
                        hit.material.absorption.w,
                        hit.material.scattering,
                        hit.material.absorption.w + hit.material.scattering,
                        0.0
                    );
                } else {
                    medium_remove();
                }
                // Update eta_scale for russian roulette
                eta_scale *= bxdf_sample.eta; 
            }

            // Sample direct light
            LiSample li_sample;
            if (!is_dirac_delta && properties.next_event_estimation == 1) {
                float piecewise_pdf = 1.0;

                LightInfo light = sample_light(random1D(prd.seed), piecewise_pdf);

                vec2 r = random2D(prd.seed);
                float mis_weight = 1.0;
                switch(light.type) {
                    case Light_Type_Area :     li_sample = sample_Li_area(origin, r, light); break;
                    case Light_Type_Infinite : li_sample = sample_Li_infinite(piecewise_pdf, r, light); break;
                }

                li_sample.pdf *= piecewise_pdf;

                if (li_sample.pdf > 0.0) {
                    vec3 wi = to_local(hit.tangent, hit.bitangent, hit.normal_s, li_sample.wi);

                    float material_random = random1D(prd.seed);
                    float bxdf_f = bxdf_f(hit.material_type, wo, wi, material_random);
                    float bxdf_pdf = bxdf_pdf(hit.material_type, wo, wi, material_random);

                    if (bxdf_f > 0.0 && bxdf_pdf > 0.0) {
                        shadow_prd.visibility = false;
                        const uint shadow_flags = gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsSkipClosestHitShaderEXT;
                        traceRayEXT(tlas, shadow_flags, 0xff, 0, 0, 1, origin, tmin, li_sample.wi, li_sample.distance * 0.99999, 1);

                        if (shadow_prd.visibility) {
                            vec3 li_transmittance = vec3(1.0);
                            if (current_medium >= 0) {
                                li_transmittance = get_transmittance(media[current_medium], li_sample.distance);
                            }
                            float mis_weight = power_heuristic(li_sample.pdf, bxdf_pdf);
                            radiance += throughput * li_transmittance * li_sample.radiance * mis_weight * bxdf_f * abs_cos_theta(wi) / li_sample.pdf;
                        }
                    }
                }
            }

            // Apply bxdf 
            if (bxdf_sample.pdf == 0.0) {
                throughput *= 0.0;
            } else {
                throughput *= bxdf_sample.f * abs_cos_theta(bxdf_sample.wi) / bxdf_sample.pdf; // TODO conductors look a little darker
            }
// TODO check how to get a compile definition to a glsl shader (maybe create a debug.glsl with a #define and include it in compilation only in debug)
//#ifdef MARI_DEBUG 
            // Check for errors
            if (isnan(direction.r)   || isnan(direction.g)  || isnan(direction.b) ||
                isnan(radiance.r)    || isnan(radiance.g)   || isnan(radiance.b)  ||
                isnan(throughput.r)  || isnan(throughput.g) || isnan(throughput.b)) {
                debugPrintfEXT(
                    "Pixel [%v2i] with NaN value:\nDepth: %i\nSample Count: %i\norigin     = %v3f\ndirection  = %v3f\nradiance   = %v3f\nthroughput = %v3f\nmaterial type   = %i\nbxdf_sample wi  = %v3f\nbxdf_sample f   = %f\nbxdf_sample pdf = %f\nli_sample wi  = %v3f\nli_sample distance = %f\nli_sample pdf = %f\n", 
                    gl_LaunchIDEXT.xy, depth, properties.frame_count, 
                    origin, direction, radiance, throughput,
                    hit.material_type, bxdf_sample.wi, bxdf_sample.f, bxdf_sample.pdf, 
                    li_sample.wi, li_sample.distance, li_sample.pdf
                );

                radiance = ERROR_COLOR;
                break;
            }
//#endif

            // Apply russian roulette
            float probability = max(max(throughput.r, throughput.g), throughput.b) * eta_scale;
            if (properties.russian_roulette == 1 && probability < 1.0 && depth > 3) {
                
                if (random1D(prd.seed) > probability) {
                    break;
                }
                throughput /= probability;
            }
        }

        result += radiance;
    }

    result /= properties.samples_per_pixel;

    if (isnan(result.r) || isnan(result.g) || isnan(result.b)) result = ERROR_COLOR;
    if (isinf(result.r) || isinf(result.g) || isinf(result.b)) result = ERROR_COLOR;

    if (properties.frame_accumulation == 1) {
        // Load existing accumulated color
        vec4 previous_color = vec4(0.0);
        if (properties.frame_count > 0) {
            previous_color = imageLoad(image, ivec2(gl_LaunchIDEXT.xy));
        }

        // Calculate new average color
        float avg = 1.0 / (properties.frame_count + 1.0);
        result = (result + previous_color.rgb * properties.frame_count) * avg;
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(result, 1.0));
    }

    // Apply tone mapping
    vec3 tonemapped_color = apply_tonemapping(properties.tonemapper, result, properties.exposure);
    imageStore(present_image, ivec2(gl_LaunchIDEXT.xy), vec4(tonemapped_color, 1.0));
}