#version 460
#extension GL_GOOGLE_include_directive : require

#include "common/raygencommon.glsl"

//#define SPECTRAL

layout(location = 0) rayPayloadEXT Payload prd;
layout(location = 1) rayPayloadEXT ShadowVolumetricPayload shadow_prd;

void main() {
    prd.seed = tea(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, properties.frame_count);
    shadow_prd.seed = prd.seed;
    vec3 result = vec3(0.0);

    const float tmin = 0.0;
    const float tmax = 10000.0;

#ifdef SPECTRAL
    float wavelength_min = 360.0f;
    float wavelength_max = 830.0f;
    prd.wavelengths = random3D(prd.seed) * (wavelength_max - wavelength_min) + wavelength_min; 
#endif

    initialize_participating_media(); // TODO make it a #define so non volumetric path tracer does not need to allocate media stuff

    for (int sample_count = 0; sample_count < properties.samples_per_pixel; sample_count++) {
        const vec2 pixel_jitter = random2D(prd.seed);
        const vec2 pixel_center = vec2(gl_LaunchIDEXT.xy) + pixel_jitter;
        const vec2 s = (pixel_center / vec2(gl_LaunchSizeEXT.xy)) * 2.0 - 1.0;

        vec4 target     =  properties.proj_inverse * vec4(s.x, s.y, 1, 1);
        vec3 origin     = (properties.view_inverse * vec4(0, 0, 0, 1)).xyz;
        vec3 direction  = (properties.view_inverse * vec4(normalize(target.xyz), 0)).xyz;
        vec3 radiance   = vec3(0.0);
        vec3 throughput = vec3(1.0);

        float previous_pdf = 1.0;
        float eta_scale = 1.0;
        bool is_dirac_delta = true;
        bool inside_dielectric = false;

        for (uint depth = 0; depth < properties.max_depth; depth++) {
            traceRayEXT(tlas, gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, origin, tmin, direction, tmax, 0);
            
            Hit hit;
            hit.material.medium.absorption = 0;
            hit.material.medium.scattering = 0; // TODO zero valued hit object
            
            bool hit_surface = false;
            if (prd.instance_index >= 0) {
                hit         = process_hit(prd);
                material    = hit.material;
                hit_surface = true;
                if (prd.barycentrics.y < 0) { //TODO duplicate from process_hit
                    hit.position = origin + direction * hit.t;
                    hit.material_type = MaterialType_Boundary;
                    hit.material.medium = volume.medium;
                }
            }
            vec3 wo;
            BxdfSample bxdf_sample;

            const bool is_backface = dot(direction, hit.normal_g) > 0.0;
            
            // If the ray hits the backface of a volume boundary and the medium is not present, 
            // then it means the camera is inside some medium that's not being accounted for, therefore add it retroactively
            if ((hit.material.medium.scattering > 0.0 || hit.material.medium.absorption > 0.0) && current_medium < 0 && is_backface) {
                medium_push(hit.material.medium);
            }

            // TODO test intersections with every nanovdb bbox, get a list of results and sample them accordingly
            // Sample the participating medium
            MediumEvent medium_event = sample_medium_along_ray(origin, direction, hit.t, prd.seed);
            throughput *= medium_event.transmittance;

            /********************************
             * Medium interaction
             ********************************/

            // Apply emission with MIS (for when emission is treated as directly related to absorption)
            if (medium_event.terminated || medium_event.scattered) {
                // Applying MIS algebra results in the scattered event algebra simplifying to equal the absorption event
                // Therefore we can skip MIS altogether and do this instead for both events
                float p_a = medium_event.sampl.sigma_a / (medium_event.sampl.sigma_a + medium_event.sampl.sigma_s);
                radiance += throughput * p_a * medium_event.sampl.emission;

                // If emission is supposed to be independent of absorption density
                //radiance += throughput * medium_event.sampl.emission / (medium_event.sampl.sigma_a + medium_event.sampl.sigma_s);
            }
            
            if (medium_event.terminated) {
                //radiance += throughput * medium_event.sampl.emission;
                break;
            }
            if (medium_event.scattered) {
                if (medium_event.pf.pdf == 0.0) 
                    break;

                wo = -direction;
                // Set values for next ray
                origin          = origin + direction * medium_event.t;
                direction       = medium_event.pf.wi;
                throughput     *= medium_event.sampl.albedo;
                previous_pdf    = medium_event.pf.pdf;
                is_dirac_delta  = false;
            }
            /********************************
             * Surface interaction
             ********************************/
            else if (hit_surface) {
                // Hit a volume boundary. Keep going without interacting.
                if (hit.material_type == MaterialType_Boundary) {
                    const bool entering = !is_backface;

                    origin = hit.position; //origin = offset_position(hit.position, entering ? -hit.normal_g : hit.normal_g); // TODO do we need to offset?
                    if (entering) {
                        medium_push(hit.material.medium);
                    } else {
                        medium_remove();
                    }
                    continue;
                }
                
                // Render backfaces
                if (is_backface && hit.material_type != MaterialType_Dielectric) {
                    flip_orientation(hit);
                }

                bool is_emissive = length_squared(hit.material.emission.rgb) > 0.0;
                if (is_emissive && !hit.material.double_sided_emission) {
                    is_emissive = !is_backface;
                }

                // Sample indirect light
                if (is_emissive) {
                    radiance += throughput * hit.material.emission.rgb;
                }

                // Sample bxdf
                wo = to_local(hit.tangent, hit.bitangent, hit.normal_s, -direction);
                bxdf_sample = bxdf_sample_material(hit.material_type, wo, prd.seed);
                if (bxdf_sample.failed) {
                    break;
                }

                // TODO directly multiply transmittance if not using a multiple scattering medium technique like delta tracking
                // ie when absorption is higher than zero, but scattering is zero

                // Set values for next ray
                throughput    *= hit.material.albedo.rgb;
                is_dirac_delta = bxdf_sample.is_dirac_delta;
                previous_pdf   = bxdf_sample.pdf;
                direction      = from_local(hit.tangent, hit.bitangent, hit.normal_s, bxdf_sample.wi);

                // If next ray goes inside non dielectric object, consider it absorbed
                bool going_inside = dot(direction, hit.normal_g) < 0.0;
                if (hit.material_type != MaterialType_Dielectric && going_inside) break;
                origin = offset_position(hit.position, going_inside ? -hit.normal_g : hit.normal_g);

                // Add or remove medium in stack when entering or exiting dielectric
                if (bxdf_sample.is_transmission) { // TODO only if medium majorant > 0.0
                    if (going_inside) {
                        medium_push(hit.material.medium);
                        inside_dielectric = !hit.material.dielectric_nee_cheat;
                    } else {
                        medium_remove();
                        inside_dielectric = false;
                    }
                    // Update eta_scale for russian roulette
                    eta_scale *= bxdf_sample.eta; 
                }
            }

            /********************************
             * Apply bounce throughput for next ray
            /********************************/
            if (medium_event.scattered) {
                // Phase Function
                throughput *= medium_event.pf.p / medium_event.pf.pdf;
            } else if (hit_surface) {
                // Bxdf
                if (bxdf_sample.pdf <= 0.0) {
                    throughput *= 0.0;
                } else {
                    throughput *= bxdf_sample.f * abs_cos_theta(bxdf_sample.wi) / bxdf_sample.pdf; // TODO conductors look a little darker
                }
            }

            /********************************
             * Miss. Sample environment map
             ********************************/
            if (!hit_surface) {
                vec2 uv;
                vec3 le = sample_Le_infinite(direction, uv);
                radiance += throughput * le;
                break;
            }

        }

        result += radiance;
    }

    result /= properties.samples_per_pixel;

    if (isnan(result.r) || isnan(result.g) || isnan(result.b)) result = ERROR_COLOR;
    if (isinf(result.r) || isinf(result.g) || isinf(result.b)) result = ERROR_COLOR;

    if (properties.frame_accumulation) {
        // Load existing accumulated color
        vec4 previous_color = vec4(0.0);
        if (properties.frame_count > 0) {
            previous_color = imageLoad(image, ivec2(gl_LaunchIDEXT.xy));
        }

        // Calculate new average color
        float avg = 1.0 / (properties.frame_count + 1.0);
        result = (result + previous_color.rgb * properties.frame_count) * avg;
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(result, 1.0));
    }

    // Apply tone mapping
    vec3 tonemapped_color = apply_tonemapping(properties.tonemapper, result, properties.exposure);
    imageStore(present_image, ivec2(gl_LaunchIDEXT.xy), vec4(tonemapped_color, 1.0));
}