#version 460
#extension GL_GOOGLE_include_directive : require

#include "common/raygencommon.glsl"

//#define SPECTRAL

layout(location = 0) rayPayloadEXT Payload prd;
layout(location = 1) rayPayloadEXT ShadowVolumetricPayload shadow_prd;

void main() {
    prd.seed = tea(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, properties.frame_count);
    shadow_prd.seed = prd.seed;
    vec3 result = vec3(0.0);

    const float tmin = 0.0;
    const float tmax = 10000.0;
    const uint  shadow_flags = gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsSkipClosestHitShaderEXT;

#ifdef SPECTRAL
    float wavelength_min = 360.0f;
    float wavelength_max = 830.0f;
    prd.wavelengths = random3D(prd.seed) * (wavelength_max - wavelength_min) + wavelength_min; 
#endif

    initialize_participating_media(); // TODO make it a #define so non volumetric path tracer does not need to allocate media stuff

    for (int sample_count = 0; sample_count < properties.samples_per_pixel; sample_count++) {
        const vec2 pixel_jitter = random2D(prd.seed);
        const vec2 pixel_center = vec2(gl_LaunchIDEXT.xy) + pixel_jitter;
        const vec2 s = (pixel_center / vec2(gl_LaunchSizeEXT.xy)) * 2.0 - 1.0;

        vec4 target     =  properties.proj_inverse * vec4(s.x, s.y, 1, 1);
        vec3 origin     = (properties.view_inverse * vec4(0, 0, 0, 1)).xyz;
        vec3 direction  = (properties.view_inverse * vec4(normalize(target.xyz), 0)).xyz;
        vec3 radiance   = vec3(0.0);
        vec3 throughput = vec3(1.0);

        float previous_pdf = 1.0;
        float eta_scale = 1.0;
        bool regularize = false;
        float r_u = 1.0;
        float r_l = 1.0;
        bool is_dirac_delta = true;
        bool inside_dielectric = false;

        for (uint depth = 0; depth < properties.max_depth; depth++) {
            float t = tmax;
            traceRayEXT(tlas, gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, origin, tmin, direction, t, 0);

            Hit hit;
            bool hit_surface = false;
            if (prd.instance_index >= 0) {
                hit         = process_hit(prd);
                t           = length(hit.position - origin);
                material    = hit.material;
                hit_surface = true;
            }
            vec3 wo;
            BxdfSample bxdf_sample;

            // TODO test intersections with every nanovdb bbox, get a list of results and sample them accordingly
            // Sample the participating medium
            MediumEvent medium_event = sample_medium_along_ray(origin, direction, t, prd.seed);

            // Compute throughput' at new path vertex
            //float pdf = 
            // TODO is it spectral only?
            // Compute rescaled path probability for absorption at path vertex
            //float r_e = r_u * 

            /********************************
             * Medium interaction
             ********************************/
            if (medium_event.terminated) {
                break; // TODO THESIS can emission be added in both absorption and scattering events with MIS?
            }
            if (medium_event.scattered) {
                // TODO why does emission only happen acording to the coefficient of absorption? Use MIS?
                radiance += throughput * medium_event.medium.absorption * medium_event.sampl.emission; /* / r_e; */

                if (medium_event.pf.pdf == 0.0) 
                    break;

                wo = -direction;
                // Set values for next ray
                origin          = origin + direction * medium_event.t;
                direction       = medium_event.pf.wi;
                throughput     *= medium_event.sampl.albedo;
                r_l             = r_u / medium_event.pf.pdf;
                previous_pdf    = medium_event.pf.pdf;
                is_dirac_delta  = false;

                // TODO light sample context?
                //continue;
                // TODO null scatters have to update tracking variables
            } 
            /********************************
             * Surface interaction
             ********************************/
            else if (hit_surface) {
                const bool is_backface = dot(direction, hit.normal_g) > 0.0;

                // Hit a volume boundary. Keep going without interacting.
                if (hit.material_type == MaterialType_Boundary) {
                    const bool entering = !is_backface;

                    origin = offset_position(hit.position, entering ? -hit.normal_g : hit.normal_g);
                    if (entering) {
                        medium_push(hit.material.medium);
                    } else {
                        medium_remove();
                    }
                    continue;
                }
                
                // Render backfaces
                if (is_backface && hit.material_type != MaterialType_Dielectric) {
                    flip_orientation(hit);
                }

                bool is_emissive = length_squared(hit.material.emission.rgb) > 0.0;
                if (is_emissive && !hit.material.double_sided_emission) {
                    is_emissive = !is_backface;
                }

                // Sample indirect light
                if (is_emissive) {
                    if (is_dirac_delta || !properties.next_event_estimation) {
                        radiance += throughput * hit.material.emission.rgb;
                    }                 
                    else {
                        float light_mis = pdf_light_area(hit.vertices, direction, t, hit.material.emission.rgb, hit.material.double_sided_emission);
                        float scatter_mis = previous_pdf;
                        radiance += throughput * hit.material.emission.rgb * power_heuristic(scatter_mis, light_mis);
                    }
                }

                // Sample bxdf
                wo = to_local(hit.tangent, hit.bitangent, hit.normal_s, -direction);
                bxdf_sample = bxdf_sample_material(hit.material_type, wo, prd.seed);
                if (bxdf_sample.failed) {
                    break;
                }

                // TODO directly multiply transmittance if not using a multiple scattering medium technique like delta tracking
                // ie when absorption is higher than zero, but scattering is zero

                // Set values for next ray
                throughput    *= hit.material.albedo.rgb;
                is_dirac_delta = bxdf_sample.is_dirac_delta;
                previous_pdf   = bxdf_sample.pdf;
                direction      = from_local(hit.tangent, hit.bitangent, hit.normal_s, bxdf_sample.wi);

                // If next ray goes inside non dielectric object, consider it absorbed
                bool going_inside = dot(direction, hit.normal_g) < 0.0;
                if (hit.material_type != MaterialType_Dielectric && going_inside) break;
                origin = offset_position(hit.position, going_inside ? -hit.normal_g : hit.normal_g);

                // Add or remove medium in stack when entering or exiting dielectric
                if (bxdf_sample.is_transmission) { // TODO only if medium majorant > 0.0
                    if (going_inside) {
                        medium_push(hit.material.medium);
                        inside_dielectric = !hit.material.dielectric_nee_cheat;
                    } else {
                        medium_remove();
                        inside_dielectric = false;
                    }
                    // Update eta_scale for russian roulette
                    eta_scale *= bxdf_sample.eta; 
                }
            }

            /********************************
             * Next Event Estimation
             * Sample direct light
             ********************************/
            LiSample li_sample;
            if ((hit_surface || medium_event.scattered) && !is_dirac_delta /*&& !inside_dielectric*/ && properties.next_event_estimation) {
                float piecewise_pdf = 1.0;

                LightInfo light = sample_light(random1D(prd.seed), piecewise_pdf);

                vec2 r = random2D(prd.seed);
                float mis_weight = 1.0;
                switch(light.type) {
                    case Light_Type_Area :     li_sample = sample_Li_area(origin, r, light); break;
                    case Light_Type_Infinite : li_sample = sample_Li_infinite(piecewise_pdf, r, light); break;
                }

                li_sample.pdf *= piecewise_pdf;

                if (li_sample.pdf > 0.0) {
                    vec3 wi = vec3(0.0);
                    float scatter_f   = 0.0;
                    float scatter_pdf = 0.0;
                    float lobe_random = random1D(prd.seed);
                    if (medium_event.scattered) {
                        wi = li_sample.wi;
                        scatter_f   = pf_eval_p  (medium_event.medium.phase_function, wo, wi, lobe_random);
                        scatter_pdf = pf_eval_pdf(medium_event.medium.phase_function, wo, wi, lobe_random);
                    } else {
                        wi = to_local(hit.tangent, hit.bitangent, hit.normal_s, li_sample.wi);
                        scatter_f   = bxdf_f  (hit.material_type, wo, wi, lobe_random) * abs_cos_theta(wi);
                        scatter_pdf = bxdf_pdf(hit.material_type, wo, wi, lobe_random);
                    }

                    if (scatter_f > 0.0 && scatter_pdf > 0.0) {
                        shadow_prd.visibility = false;
                        shadow_prd.hit_count = 0;
                        float shadow_tmax = li_sample.distance  * 0.99999;

                        traceRayEXT(tlas, shadow_flags, 0xff, 1, 32 /*TODO bring SBT stride from host*/, 1, origin, tmin, li_sample.wi, shadow_tmax, 1);

                        if (shadow_prd.visibility) {
                            vec3 li_transmittance = vec3(1.0);

                            float stmin = 0.0;
                            float stmax = shadow_tmax;

                            /********************************
                             * Volume Boundary Meshes
                             ********************************/
                            if (shadow_prd.hit_count > 0) {
                                sort_hits(shadow_prd.hits, shadow_prd.hit_count);

                                // If amount of boundary hits is even, it means the ray starts outside of a medium
                                // therefore skip the first section of the ray for transmittance calculation
                                // If the light happens to be inside a medium, then the opposite is true
                                // breaks if there's volumes inside of volumes
                                int start = shadow_prd.hit_count % 2 == 0 ? 1 : 0;
                                if (light.inside_media) {
                                    start == 0 ? 1 : 0;
                                    shadow_prd.hits[shadow_prd.hit_count].t = shadow_tmax;
                                    shadow_prd.hits[shadow_prd.hit_count].material_bda = shadow_prd.hits[shadow_prd.hit_count - 1].material_bda;
                                    shadow_prd.hit_count++; // TODO find a cleaner way to handle this
                                }

                                for (int i = start; i < shadow_prd.hit_count; i += 2) {
                                    medium_push(get_material(shadow_prd.hits[i].material_bda).constants.medium);

                                    if (i == 0) {
                                        stmax = shadow_prd.hits[i].t;
                                    } else {
                                        stmin = shadow_prd.hits[i - 1].t;
                                        stmax = shadow_prd.hits[i].t;
                                    }

                                    if (stmax - stmin > 0.0) {
                                        li_transmittance *= sample_transmittance_along_ray(origin, li_sample.wi, stmin, stmax, prd.seed, properties.transmittance_algo);
                                    }
                                    medium_remove();
                                }
                            }
                            // The scattered point and the light are both inside the same volumetric boundary 
                            else if (light.inside_media) {
                                li_transmittance *= sample_transmittance_along_ray(origin, li_sample.wi, 0.0, shadow_tmax, prd.seed, properties.transmittance_algo);
                            }
                            /********************************
                             * NanoVDB
                             ********************************/
                            stmin = 0.0;
                            stmax = shadow_tmax;

                            if (test_intersection_volume_nano(origin, li_sample.wi, stmin, stmax)) {
                                medium_push(volume.medium);
                                li_transmittance *= sample_transmittance_along_ray(origin, li_sample.wi, stmin, stmax, prd.seed, properties.transmittance_algo);
                                medium_remove();
                            }

                            float mis_weight = power_heuristic(li_sample.pdf, scatter_pdf);
                            radiance += throughput * li_transmittance * li_sample.radiance * mis_weight * scatter_f / li_sample.pdf;
                        }
                    }
                }
            }
            /********************************
             * Apply bounce throughput for next ray
            /********************************/
            if (medium_event.scattered) {
                // Phase Function
                throughput *= medium_event.pf.p / medium_event.pf.pdf;
                continue;
            } else if (hit_surface) {
                // Bxdf
                if (bxdf_sample.pdf == 0.0) {
                    throughput *= 0.0;
                } else {
                    throughput *= bxdf_sample.f * abs_cos_theta(bxdf_sample.wi) / bxdf_sample.pdf; // TODO conductors look a little darker
                    r_l = r_u / bxdf_sample.pdf;
                }
            }

            /********************************
             * Miss. Sample environment map
             ********************************/
            if (!hit_surface) {
                vec2 uv;
                vec3 le = sample_Le_infinite(direction, uv);
                float mis_weight = 1.0;
                if (!is_dirac_delta && properties.next_event_estimation) {
                    mis_weight = power_heuristic(previous_pdf, pdf_light_infinite(uv));
                }

                if (!isnan(mis_weight)) radiance += throughput * le * mis_weight;
                break;            
            }
            /********************************
             * Russian roulette
             ********************************/
            float probability = max(max(throughput.r, throughput.g), throughput.b) * eta_scale;
            if (properties.russian_roulette && probability < 1.0 && depth > 3) {
                
                if (random1D(prd.seed) > probability) {
                    break;
                }
                throughput /= probability;
            }

        }

        result += radiance;
    }

    result /= properties.samples_per_pixel;

    if (isnan(result.r) || isnan(result.g) || isnan(result.b)) result = ERROR_COLOR;
    if (isinf(result.r) || isinf(result.g) || isinf(result.b)) result = ERROR_COLOR;

    if (properties.frame_accumulation) {
        // Load existing accumulated color
        vec4 previous_color = vec4(0.0);
        if (properties.frame_count > 0) {
            previous_color = imageLoad(image, ivec2(gl_LaunchIDEXT.xy));
        }

        // Calculate new average color
        float avg = 1.0 / (properties.frame_count + 1.0);
        result = (result + previous_color.rgb * properties.frame_count) * avg;
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(result, 1.0));
    }

    // Apply tone mapping
    vec3 tonemapped_color = apply_tonemapping(properties.tonemapper, result, properties.exposure);
    imageStore(present_image, ivec2(gl_LaunchIDEXT.xy), vec4(tonemapped_color, 1.0));
}