#version 460
#extension GL_GOOGLE_include_directive                      : require
//#ifdef MARI_DEBUG 
#extension GL_EXT_debug_printf                              : enable
//#endif

#include "common/material.glsl"
MaterialConstants material;
#include "common/bxdf.glsl"
#include "common/sampling.glsl"
#include "common/raycommon.glsl"
#include "common/hitcommon.glsl"
#include "common/tonemapping.glsl"
#include "common/light.glsl"
#include "common/volume.glsl"

layout(binding = 0, set = 0) uniform accelerationStructureEXT tlas;
layout(binding = 1, set = 0, rgba32f) uniform image2D image;
layout(binding = 2, set = 0, rgba8) uniform image2D present_image;
layout(binding = 8, set = 0) uniform sampler2D textures[];

layout(location = 0) rayPayloadEXT Payload prd;
layout(location = 1) rayPayloadEXT ShadowPayload shadow_prd;

layout(binding = 3, set = 0, scalar) uniform Properties {
    mat4  view_inverse;
    mat4  proj_inverse;
    int   frame_count;
    int   max_depth;
    float exposure;
    int   tonemapper;
    int   frame_accumulation;
    int   russian_roulette;
    int   next_event_estimation;
    int   samples_per_pixel;
} properties;


#define ERROR_COLOR vec3(5000.0, 0.0, 5000.0)

void main() {
    prd.seed = tea(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, properties.frame_count);
    vec3 result = vec3(0.0);

    const float tmin = 0.0;
    const float tmax = 10000.0;

    initialize_volume_nano();

    for (int sample_count = 0; sample_count < properties.samples_per_pixel; sample_count++) {
        const vec2 pixel_jitter = random2D(prd.seed);
        const vec2 pixel_center = vec2(gl_LaunchIDEXT.xy) + pixel_jitter;
        const vec2 s = (pixel_center / vec2(gl_LaunchSizeEXT.xy)) * 2.0 - 1.0;

        vec4 target     =  properties.proj_inverse * vec4(s.x, s.y, 1, 1);
        vec3 origin     = (properties.view_inverse * vec4(0, 0, 0, 1)).xyz;
        vec3 direction  = (properties.view_inverse * vec4(normalize(target.xyz), 0)).xyz;
        vec3 radiance   = vec3(0.0);
        vec3 throughput = vec3(1.0);
        bool is_volume  = false;

        float previous_pdf = 1.0;
        float eta_scale = 1.0;
        bool regularize = false;
        float r_u = 1.0;
        float r_l = 1.0;
        bool is_dirac_delta = false;

        for (uint depth = 0; depth < properties.max_depth; depth++) {
            float t = tmax;
            traceRayEXT(tlas, gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, origin, tmin, direction, t, 0);

            Hit hit;
            bool hit_surface = false;
            if (prd.instance_index >= 0) {
                hit         = process_hit(prd);
                t           = length(hit.position - origin);
                material    = hit.material;
                hit_surface = true;
            }
            vec3 wo;
            BxdfSample bxdf_sample;

            // TODO test intersections with every nanovdb bbox, get a list of results and sample them accordingly
            // Sample the participating medium
            // if (medium) {
            MediumEvent medium_event = sample_medium_along_ray(origin, direction, t, prd.seed);
            // Compute throughput' at new path vertex
            //float pdf = 
            // TODO is it spectral only?
            // Compute rescaled path probability for absorption at path vertex
            //float r_e = r_u * 

            if (medium_event.terminated) {
                break; // TODO THESIS can emission be added in both absorption and scattering events with MIS?
            }
            if (medium_event.scattered) {
                // TODO why does emission only happen acording to the coefficient of absorption
                radiance += throughput * medium_event.medium.absorption * medium_event.sampl.emission; /* / r_e; */

                //float pdf =

                // Sample next event estimation (direct lighting)
                // TODO
                wo = -direction;


                if (medium_event.pf.pdf == 0.0) 
                    break;
                // Set values for next ray
                origin     = origin + direction * medium_event.t;
                direction  = medium_event.pf.wi;
                throughput *= medium_event.sampl.albedo * medium_event.pf.p / medium_event.pf.pdf;
                r_l = r_u / medium_event.pf.pdf;
                previous_pdf = medium_event.pf.pdf;
                is_dirac_delta = false;
                // TODO light sample context?
                //continue;
                // TODO null scatters have to update tracking variables
            } else if (hit_surface) {

                // if (hit.material_type == MaterialType_Boundary) {} // TODO
                
                // Render backfaces
                if (dot(direction, hit.normal_g) > 0.0 && hit.material_type != MaterialType_Dielectric) {
                    flip_orientation(hit);
                }

                const bool is_emissive = length_squared(hit.material.emission.rgb) > 0.0;

                // Sample indirect light
                if (is_emissive) {
                    if (depth == 0 || is_dirac_delta || properties.next_event_estimation == 0) {
                        // TODO if single side -> if dot(normal_g, -prd.direction) > 0.0
                        radiance += throughput * hit.material.emission.rgb;
                    }                 
                    else {
                        float light_mis = pdf_light_area(hit.vertices, direction, t, hit.material.emission.rgb, true); // TODO double sided parameter in material
                        float bxdf_mis = previous_pdf;
                        radiance += throughput * hit.material.emission.rgb * power_heuristic(bxdf_mis, light_mis);
                    }
                }

                // Sample bxdf
                wo = to_local(hit.tangent, hit.bitangent, hit.normal_s, -direction);
                bxdf_sample = bxdf_sample_material(hit.material_type, wo, prd.seed);
                if (bxdf_sample.failed) {
                    break;
                }

                // Set values for next ray
                throughput    *= hit.material.albedo.rgb;
                is_dirac_delta = bxdf_sample.is_dirac_delta;
                previous_pdf   = bxdf_sample.pdf;
                direction      = from_local(hit.tangent, hit.bitangent, hit.normal_s, bxdf_sample.wi);
                // If next ray goes inside non dielectric object, consider it absorbed
                bool going_inside = dot(direction, hit.normal_g) < 0.0;
                if (hit.material_type != MaterialType_Dielectric && going_inside) break;
                origin = offset_position(hit.position, going_inside ? -hit.normal_g : hit.normal_g);

                // TODO transmission, eta_scale, etc
            }

            // Sample direct light
            LiSample li_sample;
            if (!is_dirac_delta && properties.next_event_estimation == 1) {
                float piecewise_pdf = 1.0;

                LightInfo light = sample_light(random1D(prd.seed), piecewise_pdf);

                vec2 r = random2D(prd.seed);
                float mis_weight = 1.0;
                switch(light.type) {
                    case Light_Type_Area :     li_sample = sample_Li_area(origin, r, light); break;
                    case Light_Type_Infinite : li_sample = sample_Li_infinite(piecewise_pdf, r, light); break;
                }

                li_sample.pdf *= piecewise_pdf;

                if (li_sample.pdf > 0.0) {
                    vec3 wi;
                    float scatter_f, scatter_pdf;
                    
                    if (medium_event.scattered) {
                        wi = li_sample.wi;
                        scatter_f = pf_henyey_greenstein_p(wo, wi, medium_event.medium.g);
                        scatter_pdf = pf_henyey_greenstein_pdf(wo, wi, medium_event.medium.g);
                    } else {
                        wi = to_local(hit.tangent, hit.bitangent, hit.normal_s, li_sample.wi);
                        float material_random = random1D(prd.seed);
                        scatter_f = bxdf_f(hit.material_type, wo, wi, material_random) * abs_cos_theta(wi);
                        scatter_pdf = bxdf_pdf(hit.material_type, wo, wi, material_random);
                    }


                    if (scatter_f > 0.0 && scatter_pdf > 0.0) {
                        shadow_prd.visibility = false;
                        const uint shadow_flags = gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsSkipClosestHitShaderEXT;
                        traceRayEXT(tlas, shadow_flags, 0xff, 0, 0, 1, origin, tmin, li_sample.wi, li_sample.distance * 0.99999, 1);

                        if (shadow_prd.visibility) {
                            vec3 li_transmittance = vec3(1.0);
                            //if (current_medium >= 0) {
                            //    li_transmittance = get_transmittance(media[current_medium], li_sample.distance);
                            //}


                            // TODO weird bug with volume nee depending on the octant of direction
                            li_transmittance = sample_medium_along_ray(origin, li_sample.wi, t, prd.seed).transmittance;

                            float mis_weight = power_heuristic(li_sample.pdf, scatter_pdf);
                            radiance += throughput * li_transmittance * li_sample.radiance * mis_weight * scatter_f / li_sample.pdf;
                        }
                    }
                }
            }

            if (medium_event.scattered) {
                continue;
            } else if (hit_surface) {
                // Apply bxdf
                if (bxdf_sample.pdf == 0.0) {
                    throughput *= 0.0;
                } else {
                    throughput *= bxdf_sample.f * abs_cos_theta(bxdf_sample.wi) / bxdf_sample.pdf; // TODO conductors look a little darker
                    r_l = r_u / bxdf_sample.pdf;
                }
            }


            // Miss. Sample environment map
            if (!hit_surface) {
                vec2 uv;
                vec3 le = sample_Le_infinite(direction, uv);
                float mis_weight = 1.0;
                if (!is_dirac_delta && depth != 0 && properties.next_event_estimation == 1) {
                    mis_weight = power_heuristic(previous_pdf, pdf_light_infinite(uv));
                }

                if (!isnan(mis_weight)) radiance += throughput * le * mis_weight;
                break;            
            }

            // Apply russian roulette
            float probability = max(max(throughput.r, throughput.g), throughput.b) * eta_scale;
            if (properties.russian_roulette == 1 && probability < 1.0 && depth > 3) {
                
                if (random1D(prd.seed) > probability) {
                    break;
                }
                throughput /= probability;
            }

        }

        result += radiance;
    }

    result /= properties.samples_per_pixel;

    if (isnan(result.r) || isnan(result.g) || isnan(result.b)) result = ERROR_COLOR;
    if (isinf(result.r) || isinf(result.g) || isinf(result.b)) result = ERROR_COLOR;

    if (properties.frame_accumulation == 1) {
        // Load existing accumulated color
        vec4 previous_color = vec4(0.0);
        if (properties.frame_count > 0) {
            previous_color = imageLoad(image, ivec2(gl_LaunchIDEXT.xy));
        }

        // Calculate new average color
        float avg = 1.0 / (properties.frame_count + 1.0);
        result = (result + previous_color.rgb * properties.frame_count) * avg;
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(result, 1.0));
    }

    // Apply tone mapping
    vec3 tonemapped_color = apply_tonemapping(properties.tonemapper, result, properties.exposure);
    imageStore(present_image, ivec2(gl_LaunchIDEXT.xy), vec4(tonemapped_color, 1.0));
}