#version 460
#extension GL_GOOGLE_include_directive : require

#include "common/raycommon.glsl"
#include "common/sampling.glsl"
#include "common/tonemapping.glsl"

layout(binding = 0, set = 0) uniform accelerationStructureEXT tlas;
layout(binding = 1, set = 0, rgba32f) uniform image2D image;
layout(binding = 2, set = 0, rgba8) uniform image2D presentImage;

layout(location = 0) rayPayloadEXT Payload prd;

void main() {
    prd.seed = tea(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, properties.frameCount);
    prd.thread = uvec3(gl_LaunchIDEXT.x, gl_LaunchIDEXT.y, 0);
    vec4 result = vec4(0.0);

    for (int sampleCount = 0; sampleCount < properties.samplesPerPixel; sampleCount++) {
        float r1 = random(prd.seed);
        float r2 = random(prd.seed);

        const vec2 pixelJitter = vec2(r1, r2);
        const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + pixelJitter;
        const vec2 inUV = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
        vec2 s = inUV * 2.0 - 1.0;

        vec4 origin     = properties.viewInverse * vec4(0, 0, 0, 1);
        vec4 target     = properties.projInverse * vec4(s.x, s.y, 1, 1);
        vec4 direction  = properties.viewInverse * vec4(normalize(target.xyz), 0);

        // tmin is 0 because position is offset along geometric normal instead. 
        // Check offsetPositionAlongNormal() for more.
        float tmin = 0.0;
        float tmax = 10000.0;

        prd.radiance    = vec3(0.0);
        prd.throughput  = vec3(1.0);
        prd.origin      = origin.xyz;
        prd.direction   = direction.xyz;
        prd.eta         = 1.0;
        prd.done        = 0;
        prd.dirac       = false;
        prd.pdf         = 1.0;

        for (prd.depth = 0; prd.done == 0 && prd.depth < properties.maxDepth; prd.depth++) {
            if (isnan(prd.direction.r) || isnan(prd.direction.g) || isnan(prd.direction.b)) {
                prd.radiance = vec3(1.0, 0.0, 1.0);
                break;
            }

            // TODO pass gl_RayFlagsOpaqueEXT from uniforms when there is no alpha transparent material in the scene
            traceRayEXT(tlas, gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, prd.origin, tmin, prd.direction, tmax, 0);

            if (properties.russianRoulette == 1 && prd.depth > 3) { // TODO implement a minimum rr depth variable
                float probability = (prd.throughput.r + prd.throughput.g + prd.throughput.b) / 3.0;
                
                if (random(prd.seed) > probability) {
                    break; // TODO don't terminate on dielectric/transmission rays?
                }
                prd.throughput /= probability;
            }
        }

        result += vec4(prd.radiance, 1.0);
    }

    result /= properties.samplesPerPixel;

    if (isnan(result.r) || isnan(result.g) || isnan(result.b)) result = vec4(1000.0, 0.0, 1000.0, 1.0);
    if (isinf(result.r) || isinf(result.g) || isinf(result.b)) result = vec4(1000.0, 0.0, 1000.0, 1.0);

    if (properties.frameAccumulation == 1) {
        // Load existing accumulated color
        vec4 imageColor = vec4(0.0);
        if (properties.frameCount > 0) {
            imageColor = imageLoad(image, ivec2(gl_LaunchIDEXT.xy));
        }

        // Calculate new average color
        float avg = 1.0 / (properties.frameCount + 1.0);
        result = (result + imageColor * properties.frameCount) * avg;
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), result);
    }

    // Apply tone mapping
    vec3 tonemappedColor = result.rgb;
    switch (properties.tonemapper) {
        case 1: tonemappedColor = toneACES(tonemappedColor, properties.exposure); break;
        case 2: tonemappedColor = toneAgX(tonemappedColor, properties.exposure); break;
    }
    imageStore(presentImage, ivec2(gl_LaunchIDEXT.xy), vec4(tonemappedColor, 1.0));
}
