#version 460
#extension GL_GOOGLE_include_directive  : require
#extension GL_EXT_buffer_reference2     : require
#extension GL_EXT_scalar_block_layout   : require
#extension GL_EXT_nonuniform_qualifier  : require

#include "common/medium.glsl"
#include "common/material.glsl"
#include "common/raycommon.glsl"
#include "common/hitcommon.glsl"
#include "common/sampling.glsl"

layout(location = 1) rayPayloadInEXT ShadowVolumetricPayload prd;
hitAttributeEXT vec2 attribs;

void main() {
    uint64_t prim_mesh_bda = pPrimMeshInfos.addresses[gl_InstanceID];
    PrimMeshInfo primMeshInfo = PrimMeshInfos(prim_mesh_bda).p[gl_GeometryIndexEXT];
    MaterialData material = get_material(primMeshInfo.material_bda);

    uint material_type = get_material_type(material.constants);
    if (material_type == MaterialType_Boundary || material_type == MaterialType_Dielectric) {
        prd.hit_count++;
        if (prd.hit_count <= SHADOW_VOLUMETRIC_MAX_HITS) {
            prd.hits[prd.hit_count - 1].t = gl_HitTEXT;
            prd.hits[prd.hit_count - 1].material_bda = primMeshInfo.material_bda;
        }

        ignoreIntersectionEXT;
        return;
    }

    float alpha = material.constants.albedo.a;
    if (material.indices.albedo < 0 && alpha >= 1.0) {
        terminateRayEXT;
        return;
    }

    Indices indices   = Indices(primMeshInfo.indices_bda);
    Vertices vertices = Vertices(primMeshInfo.vertices_bda);
    vec3 barycentric_coords = vec3(1.0 - attribs.x - attribs.y, attribs.x, attribs.y);

    vec2 uv0 = vertices.v[indices.i[gl_PrimitiveID * 3 + 0]].uv;
    vec2 uv1 = vertices.v[indices.i[gl_PrimitiveID * 3 + 1]].uv;
    vec2 uv2 = vertices.v[indices.i[gl_PrimitiveID * 3 + 2]].uv;

    vec2 uv  = uv0 * barycentric_coords.x + uv1 * barycentric_coords.y + uv2 * barycentric_coords.z;
    if (material.indices.albedo > 0) {
        alpha *= texture(textures[nonuniformEXT(material.indices.albedo)], uv).a;
    }

    if(random1D(prd.seed) > alpha) {
        ignoreIntersectionEXT;
    } else {
        terminateRayEXT;
    }
}
