#version 460

#extension GL_EXT_ray_tracing : require

hitAttributeEXT vec2 attribs;

float intersect_aabb(const vec3 aabb_min, const vec3 aabb_max, const vec3 origin, const vec3 direction)
{
    vec3  invDir = 1.0 / direction;
    vec3  tbot   = invDir * (aabb_min - origin);
    vec3  ttop   = invDir * (aabb_max - origin);
    vec3  tmin   = min(ttop, tbot);
    vec3  tmax   = max(ttop, tbot);
    float t0     = max(tmin.x, max(tmin.y, tmin.z));
    float t1     = min(tmax.x, min(tmax.y, tmax.z));
    return t1 > max(t0, 0.0) ? t0 : -1.0;
}

void main() {
    attribs = vec2(-1,-1);

    float t = -1.0;

    t = intersect_aabb(vec3(-1.0), vec3(1.0), gl_WorldRayOriginEXT, gl_WorldRayDirectionEXT);
    if (t > 0) {
        reportIntersectionEXT(t, 0);
    }

    //reportIntersectionEXT(1, 0);
}