#version 460

#extension GL_EXT_ray_tracing                               : require
#extension GL_EXT_buffer_reference2                         : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64    : require
#extension GL_EXT_scalar_block_layout                       : require
#extension GL_EXT_nonuniform_qualifier                      : require

struct AABB {
    vec3 min;
    vec3 max;
};

layout(binding = 8, set = 0) buffer AABB_bdas { uint64_t addresses[]; } aabb_bdas;
layout(buffer_reference, scalar) readonly buffer AABBs { AABB a[]; };

hitAttributeEXT vec2 attribs;

bool intersect_aabb(const AABB aabb, const vec3 origin, const vec3 direction, inout float t, inout uint face) {
    vec3  invDir = 1.0 / direction;
    vec3  tbot   = invDir * (aabb.min - origin);
    vec3  ttop   = invDir * (aabb.max - origin);
    vec3  tmin   = min(ttop, tbot);
    vec3  tmax   = max(ttop, tbot);
    float t0     = max(tmin.x, max(tmin.y, tmin.z));
    float t1     = min(tmax.x, min(tmax.y, tmax.z));

    if (t0 > t1 || t1 < 0.0)
        return false;

    //t = t0 >= 0.0 ? t0 : t1;
    //return true;

    // Get the face that was hit for calculating the face normal later
    if (t0 >= 0.0) {
        t = t0;

        if (tmin.x >= tmin.y && tmin.x >= tmin.z)
            face = direction.x > 0.0 ? 1 : 4;
        else if (tmin.y >= tmin.z)
            face = direction.y > 0.0 ? 2 : 5;
        else
            face = direction.z > 0.0 ? 3 : 6;
    }
    else {
        t = t1;

        if (tmax.x <= tmax.y && tmax.x <= tmax.z)
            face = direction.x > 0.0 ? 4 : 1;
        else if (tmax.y <= tmax.z)
            face = direction.y > 0.0 ? 5 : 2;
        else
            face = direction.z > 0.0 ? 6 : 3;
    }

    return true;
}

void main() {
    attribs = vec2(1, 0);

    float t = -1.0;

    uint64_t aabb_bda = aabb_bdas.addresses[gl_GeometryIndexEXT];
    AABB aabb = AABBs(aabb_bda).a[0];

    // Transform points from local to world positions
    vec3 p0 = (gl_ObjectToWorldEXT * vec4(aabb.min, 1.0)).xyz;
    vec3 p1 = (gl_ObjectToWorldEXT * vec4(aabb.max, 1.0)).xyz;

    // Recalculate min and max bounds in case of rotation or negative scales
    aabb.min = min(p0, p1);
    aabb.max = max(p0, p1);

    uint face;
    if (intersect_aabb(aabb, gl_WorldRayOriginEXT, gl_WorldRayDirectionEXT, t, face)) {
        attribs.y = float(face);
        reportIntersectionEXT(t, 0);
    }
}